#pragma once
#include "CoreMinimal.h"
#include "EWWEAnimationSections.generated.h"

UENUM(BlueprintType)
enum class EWWEAnimationSections : uint8 {
    WWEDEFAULT,
    WWEEND,
    WWECHARGINGHIT,
    WWECHARGEDHIT,
    WWEOFFENSIVE,
    WWEOFFENSIVESUCCESSFULLY,
    WWECOUNTERED,
    WWERIVAL,
    WWERIVALBACK,
    WWERIVALIDLE,
    WWERIVALLAUNCHED,
    WWERIVALSUCCESSFULLY,
    WWEGOODEND,
    WWEBADEND,
    WWETHIRDBAD,
    WWETHIRDDEFAULT,
    WWETHIRDGOODEND,
    WWERIVALGOODEND,
    WWERIVALBADEND,
    WWERIVALDEFAULT,
    WWEIDLE,
    WWESTARTGRAB,
    WWEIDLEGRAB,
    WWESTARTGRABBED,
    WWEIDLEGRABBED,
    WWEENDGRAB,
    WWEENDGRABBED,
    WWERECEIVEHIT,
    WWEHEAVYBADEND,
    WWEHEAVYRIVALGOODEND,
    COUNT,
};

