#pragma once
#include "CoreMinimal.h"
#include "EWWECatalogCategory.generated.h"

UENUM(BlueprintType)
enum class EWWECatalogCategory : uint8 {
    Internal,
    External,
    Featured,
    Bundle,
    Character,
    Male,
    Female,
    Vanity,
    BodyHair,
    BodyPainting,
    Chest,
    Eyes,
    FacialHair,
    FullBodyClothes,
    Gloves,
    Hairs,
    Hats,
    Heats,
    LeftLeg,
    LeftWristbandsDown,
    LeftWristbandsUp,
    Masks,
    Pants,
    Patches,
    RightLeg,
    RightWristbandsDown,
    RightWristbandsUp,
    Scars,
    Shoes,
    SkinColors,
    SuperstarOutfits,
    Tattoos,
    Teeth,
    ArenaVanity,
    Border,
    Cover,
    Crowd,
    Floor,
    Pad,
    RingMat,
    Rope,
    Turnbuckle,
    Upgradeable,
    Slot,
    Sticker,
    FullArena,
    PowerUp,
    UpgradeableItem,
};

